# -*- coding: utf-8 -*-
"""sr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_k_NVIuXLbc1W89QvZiuDK_w0XYCtPiT
"""

import multiprocessing as mp
import os

# Константы конфигурации
NUM_PROCESSES = 4             # Фиксированное количество процессов
INPUT_FILE_1 = "matrix1.txt"  # Имя первого входного файла
INPUT_FILE_2 = "matrix2.txt"  # Имя второго входного файла
INTERMEDIATE_FILE = "intermediate.txt" # Промежуточный файл
OUTPUT_FILE = "result.txt"    # Итоговый файл с матрицей

# Глобальные переменные для рабочих процессов (заполняются через initializer)
_worker_lock = None
_worker_filename = None

def init_worker(lock, filename):
    """
    Инициализирует глобальные переменные в каждом рабочем процессе.
    Используется для передачи блокировки и имени файла в пул процессов.

    :param lock: Объект блокировки (Lock) для синхронизации записи.
    :param filename: Путь к промежуточному файлу для записи.
    """
    global _worker_lock, _worker_filename
    _worker_lock = lock
    _worker_filename = filename

def read_matrix(filename):
    """
    Читает матрицу из текстового файла.
    Ожидается формат: числа разделены пробелами, строки матрицы - новыми строками.

    :param filename: Путь к файлу.
    :return: Двумерный список (матрица) и кортеж размеров (rows, cols).
    """
    matrix = []
    with open(filename, 'r', encoding='utf-8') as f:
        for line in f:
            # Пропускаем пустые строки
            if not line.strip():
                continue
            row = list(map(float, line.split()))
            matrix.append(row)

    if not matrix:
        return [], (0, 0)

    rows = len(matrix)
    cols = len(matrix[0])
    return matrix, (rows, cols)

def calculate_and_write(args):
    """
    Задача для рабочего процесса.
    Вычисляет произведение элемента и записывает результат в промежуточный файл.
    Запись защищена блокировкой для предотвращения конфликтов.

    :param args: Кортеж (i, j, val_a, val_b) - координаты и значения элементов.
    """
    i, j, val_a, val_b = args

    # Вычисление
    result = val_a * val_b

    # Запись в файл (критическая секция)
    with _worker_lock:
        with open(_worker_filename, 'a', encoding='utf-8') as f:
            # Формат: строка столбец значение
            f.write(f"{i} {j} {result}\n")
            f.flush() # Гарантируем сброс буфера на диск

def assemble_final_matrix(rows, cols):
    """
    Считывает промежуточный файл, сортирует элементы и записывает итоговую матрицу.
    Так как процессы завершаются в произвольном порядке, элементы в промежуточном
    файле не упорядочены. Эта функция восстанавливает структуру матрицы.

    :param rows: Количество строк матрицы.
    :param cols: Количество столбцов матрицы.
    """
    elements = []

    # Чтение всех вычисленных элементов
    if os.path.exists(INTERMEDIATE_FILE):
        with open(INTERMEDIATE_FILE, 'r', encoding='utf-8') as f:
            for line in f:
                parts = line.split()
                if len(parts) == 3:
                    r, c, val = int(parts[0]), int(parts[1]), float(parts[2])
                    elements.append((r, c, val))

    # Сортировка по строкам, затем по столбцам
    elements.sort(key=lambda x: (x[0], x[1]))

    # Запись в итоговый файл
    with open(OUTPUT_FILE, 'w', encoding='utf-8') as f:
        current_row = -1
        for r, c, val in elements:
            # Если перешли на новую строку, добавляем перенос (кроме первой)
            if r != current_row:
                if current_row != -1:
                    f.write("\n")
                current_row = r

            # Записываем значение (пробел перед значением, если это не первый элемент в строке)
            # Для простоты пишем пробел перед каждым, кроме самого первого в строке
            # Но так как мы обрабатываем поэлементно, проще собрать строку в памяти или писать с пробелом
            # Здесь простой вариант: пишем значение + пробел
            f.write(f"{val} ")

        # Финальный перенос строки
        if elements:
            f.write("\n")

def create_sample_files():
    """
    Вспомогательная функция для создания тестовых файлов, если их нет.
    """
    if not os.path.exists(INPUT_FILE_1):
        with open(INPUT_FILE_1, 'w') as f:
            f.write("1 2 3\n4 5 6\n")
    if not os.path.exists(INPUT_FILE_2):
        with open(INPUT_FILE_2, 'w') as f:
            f.write("7 8 9\n10 11 12\n")

def main():
    """
    Основная функция программы.
    Управляет потоком выполнения: чтение, распараллеливание, сборка результата.
    """
    # 1. Подготовка
    create_sample_files()

    # Очистка промежуточного файла перед запуском
    if os.path.exists(INTERMEDIATE_FILE):
        os.remove(INTERMEDIATE_FILE)

    # 2. Чтение входных данных
    matrix_a, dims_a = read_matrix(INPUT_FILE_1)
    matrix_b, dims_b = read_matrix(INPUT_FILE_2)

    if dims_a != dims_b:
        print(f"Ошибка: Размеры матриц не совпадают! {dims_a} vs {dims_b}")
        return

    rows, cols = dims_a
    print(f"Матрицы загружены. Размер: {rows}x{cols}. Запуск {NUM_PROCESSES} процессов...")

    # 3. Подготовка задач
    # Создаем список аргументов для каждой ячейки матрицы
    tasks = []
    for i in range(rows):
        for j in range(cols):
            tasks.append((i, j, matrix_a[i][j], matrix_b[i][j]))

    # 4. Запуск пула процессов
    # Используем Manager для создания блокировки, безопасной для передачи между процессами
    manager = mp.Manager()
    lock = manager.Lock()

    with mp.Pool(processes=NUM_PROCESSES, initializer=init_worker, initargs=(lock, INTERMEDIATE_FILE)) as pool:
        # map блокирует выполнение до завершения всех задач
        pool.map(calculate_and_write, tasks)

    print("Вычисления завершены. Сборка итогового файла...")

    # 5. Финальная сборка результата
    assemble_final_matrix(rows, cols)

    print(f"Готово. Результат записан в {OUTPUT_FILE}")
    print(f"Промежуточные данные в {INTERMEDIATE_FILE}")

if __name__ == '__main__':
    # Защита обязательна для корректной работы multiprocessing на Windows
    main()